name: post-artifact
description: |
  Creates a post in the PR linking to an artifact.
inputs:
  job-dependency:
    description: The id of the job that creates the artifact.
    required: true
  artifact-name:
    description: Message to include
    required: false
    default: 'artifact'
runs:
  using: composite
  needs: 
  runs-on: ubuntu-latest
  permissions:
      contents: read
      pull-requests: write
  env:
    GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Post comment preview
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          gh pr comment ${{ github.event.number }} --body \
            "Thank you for your contribution @${{ github.triggering_actor }}:rocket:! Your page is ready to preview :point_right: [here](https://github.com/${{github.repository}}/actions/runs/${{ github.run_id }}/artifacts/${{ needs.build.outputs.page_artifact_id }}) :point_left:!"
