name: post-artifact
description: |
  Creates a post in the PR linking to an artifact.
inputs:
  artifact-id:
    description: The id of the artifact.
    required: true
  artifact-name:
    description: Message to include
    required: false
    default: 'artifact'
runs:
  using: 'composite'
  steps:

    - name: Compose message
      id: compose
      run: |
        echo -n "Thank you for your contribution @${{ github.actor }}"> _msg.txt
        echo -n ":rocket:! Your ${{ inputs.artifact-name }} is ready ">>_msg.txt
        echo -n "for download :point_right: [here](" >> _msg.txt
        echo -n "https://github.com/${{ github.repository }}/actions/">>_msg.txt
        echo -n "runs/${{ github.run_id }}/artifacts/" >> _msg.txt 
        echo -n "${{ inputs.artifact-id }}) :point_left:!" >> _msg.txt
      shell: bash
        
    - name: Find existing comment
      run: |
        gh pr view -R ${{ github.repository }} \
          ${{ github.event.number }} -c --json body > _events.json

        python src/get-comment.py _events.json
      shell: bash

    - name: Post comment preview
      if: ${{ github.event_name == 'pull_request' }}
      run: |
        gh pr comment ${{ github.event.number }} --body-file _msg.txt
      shell: bash
