name: post-artifact
description: |
  Creates a post in the PR linking to an artifact.
  Subsequent runs will update the comment.
inputs:
  artifact-id:
    description: |
      The id of the artifact. Should be the output from
      `actions/upload-artifacts`. For example:
      steps.[name upload step].outputs.artifact-id .
    required: true
  artifact-name:
    description: Artifact name
    required: false
    default: 'artifact'
  message:
    description: |
      Message template to be posted in the PR. The message should include
      the following placeholders: { actor }, { artifact-name },
      and { artifact-url }. The { actor } placeholder will be replaced by
      the actor's username. The { artifact-name } will be replaced by the
      artifact name. The { artifact-url } will be replaced by the URL to
      the artifact.
    required: false
    default: 'Thank you for your contribution { actor } :rocket:! Your { artifact-name } is ready for download :point_right: [here]({ artifact-url }) :point_left:!'
runs:
  using: 'composite'
  steps:

    - name: Compose message
      id: compose
      run: |
        echo ${{ inputs.message }} > _msg-${{ github.sha }}.txt
        sed -i 's/{ actor }/@${{ github.actor }}/g' \
          _msg-${{ github.sha }}.txt
        sed -i 's/{ artifact-url }/${{ github.server_url }}\/${{ github.repository }}\/actions\/runs\/${{ github.run_id }}\/artifacts\/${{ inputs.artifact-id }}/g' \
          _msg-${{ github.sha }}.txt
      shell: bash
        
    - name: Get the event
      run: |
        gh pr view -R ${{ github.repository }} \
          ${{ github.event.number }} -c --json comments > \
          _events-${{ github.sha }}.json
      shell: bash

    - name: Get comment preview
      run: |
        import json
        import re

        def main(json_comments) -> str:

            # Open the JSON file and load its contents into a Python object
            with open(json_comments, 'r') as file:
                data = json.load(file)

            if (data['comments'] == []):
                return ''

            # Generating matching string
            matching_msg = "Thank you for your contribution " \
              "@${{ github.actor}}:rocket:! Your ${{ inputs.artifact-name }}" 

            # Now you can work with the 'data' object
            for i in range(len(data['comments'])):
                body = data['comments'][i]['body']
                auth = data['comments'][i]['author']['login']
                url =  data['comments'][i]['url']
                match = re.search(r'\d+$', url)

                if not match:
                    continue

                id = match.group()

                # Regex match to the body of the comment looking
                # for the expression "Thank you for your contribution"
                # if found, print the author and the body of the comment
                if (matching_msg in body) and (auth == 'github-actions'):
                    return id

            return ''

        id = main('_events-${{ github.sha }}.json')
        fn = '_ID-${{ github.sha }}'
        with (open(fn, 'w')) as file:
            file.write(id)

        with (open(fn+'_found', 'w')) as file:
            if id == '':
                file.write('false')
            else:
                file.write('true')

      shell: python {0}

    - name: Putting the contents of _msg.txt into an environment var
      id: set-env
      run: |
        echo "MSG=$(cat _msg-${{ github.sha }}.txt)" >> $GITHUB_OUTPUT
        echo "ID=$(cat _ID-${{ github.sha }})" >> $GITHUB_OUTPUT
        echo "FOUND=$(cat _ID-${{ github.sha }}_found)" >> $GITHUB_OUTPUT
      shell: bash

    # See:
    # https://docs.github.com/en/rest/issues/comments?apiVersion=2022-11-28#update-an-issue-comment
    - name: Add comment
      if: ${{ github.event_name == 'pull_request' && steps.set-env.outputs.FOUND == 'false' }}
      run: |
        echo "No comment from github-bot found, adding a new one."
        gh pr comment -R ${{ github.repository }} \
          ${{ github.event.number }} -b "${{ steps.set-env.outputs.MSG }}"
      shell: bash
    
    - name: Update comment
      if: ${{ github.event_name == 'pull_request' && steps.set-env.outputs.FOUND == 'true' }}
      run: |
        echo "Editing original comment id: ${{ steps.set-env.outputs.ID }}."
        gh api \
          --method PATCH \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${{ github.repository}}/issues/comments/${{ steps.set-env.outputs.ID }} \
          -f "body=${{ steps.set-env.outputs.MSG }}"
      shell: bash