name: post-artifact
description: |
  Creates a post in the PR linking to an artifact.
inputs:
  artifact-id:
    description: The id of the artifact.
    required: true
  artifact-name:
    description: Message to include
    required: false
    default: 'artifact'
runs:
  using: 'composite'
  steps:

    - name: Compose message
      id: compose
      run: |
        echo "Thank you for your contribution @${{ github.actor }}" > _msg.txt
        echo ":rocket:! Your ${{ inputs.artifact-name }} is ready " >> _msg.txt
        echo "for download :point_right: [here](" >> _msg.txt
        echo "https://github.com/${{ github.repository }}/actions/" >> _msg.txt
        echo "runs/${{ github.run_id }}/artifacts/" >> _msg.txt 
        echo "${{ inputs.artifact-id }}) :point_left:!" >> _msg.txt
      shell: bash
        
    - name: Post comment preview
      if: ${{ github.event_name == 'pull_request' }}
      run: |
        gh pr comment ${{ github.event.number }} --body-file _msg.txt
      shell: bash
