name: post-artifact
description: |
  Creates a post in the PR linking to an artifact.
inputs:
  artifact-id:
    description: The id of the artifact.
    required: true
  artifact-name:
    description: Message to include
    required: false
    default: 'artifact'
runs:
  using: 'composite'
  steps:

    - name: Compose message
      id: compose
      run: |
        echo -n "Thank you for your contribution @${{ github.actor }}"> _msg-${{ github.sha }}.txt
        echo -n ":rocket:! Your ${{ inputs.artifact-name }} is ready ">>_msg-${{ github.sha }}.txt
        echo -n "for download :point_right: [here](" >> _msg-${{ github.sha }}.txt
        echo -n "https://github.com/${{ github.repository }}/actions/">>_msg-${{ github.sha }}.txt
        echo -n "runs/${{ github.run_id }}/artifacts/" >> _msg-${{ github.sha }}.txt 
        echo -n "${{ inputs.artifact-id }}) :point_left:!" >> _msg-${{ github.sha }}.txt
      shell: bash
        
    - name: Get the event
      run: |
        gh pr view -R ${{ github.repository }} \
          ${{ github.event.number }} -c --json comments > \
          _events-${{ github.sha }}.json
      shell: bash

    - name: Get comment preview
      run: |
        import json
        import re

        def main(json_comments) -> str:

            # Open the JSON file and load its contents into a Python object
            with open(json_comments, 'r') as file:
                data = json.load(file)

            if (data['comments'] == []):
                return ''

            # Now you can work with the 'data' object
            for i in range(len(data['comments'])):
                body = data['comments'][i]['body']
                auth = data['comments'][i]['author']['login']
                id = re.search(r'\d+$', data['comments'][i]['url'])

                if not id:
                    return ''

                id = id.group()


                # Regex match to the body of the comment looking
                # for the expression "Thank you for your contribution"
                # if found, print the author and the body of the comment
                if "Your preview" in body and auth == 'github-actions':
                    return id

            return ''

        id = main('_events-${{ github.sha }}.json')
        fn = '_ID-${{ github.sha }}'
        with (open(fn, 'w')) as file:
            file.write(id)

        with (open(fn+'_found', 'w')) as file:
            if id == '':
                file.write('false')
            else:
                file.write('true')

      shell: python {0}

    - name: Putting the contents of _msg.txt into an environment var
      id: set-env
      run: |
        echo "MSG=$(cat _msg-${{ github.sha }}.txt)" >> $GITHUB_OUTPUT
        echo "ID=$(cat _ID-${{ github.sha }})" >> $GITHUB_OUTPUT
        echo "FOUND=$(cat _ID-${{ github.sha }}_found)" >> $GITHUB_OUTPUT
      shell: bash

    # See:
    # https://docs.github.com/en/rest/issues/comments?apiVersion=2022-11-28#update-an-issue-comment
    - name: Add comment
      if: ${{ github.event_name == 'pull_request' && steps.set-env.outputs.FOUND == 'false' }}
      run: |
        echo "The value of FOUND and id is ${{ steps.set-env.outputs.FOUND }} and ${{ steps.set-env.outputs.ID }}"
        gh pr comment -R ${{ github.repository }} \
          ${{ github.event.number }} -b "${{ steps.set-env.outputs.MSG }}"
      shell: bash
    
    - name: Update comment
      if: ${{ github.event_name == 'pull_request' && steps.set-env.outputs.FOUND == 'true' }}
      run: |
        echo "The value of FOUND and id is ${{ steps.set-env.outputs.FOUND }} and ${{ steps.set-env.outputs.ID }}"
        gh api \
          --method PATCH \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${{ github.repository}}/issues/comments/${{ steps.set-env.outputs.ID }} \
          -f "body=${{ steps.set-env.outputs.MSG }}"
      shell: bash